# Generated by Django 3.2.3 on 2021-05-24 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cfuente',
            field=models.URLField(blank=True, null=True, verbose_name='Codigo fuente'),
        ),
    ]
